### PR TITLE
On guest provisioning

### PR DESCRIPTION
**Pull request by cermmik**
A lot of changes were made. Please check if everything is OK.

### CODE REVIEW

**Comment by tomjirsa** [comment]
TODO: Need to update main readme for new provisioning
 - when doing local provisioning - machines need an internet access

**Comment by tomjirsa** [comment]
cp remote_src: true does not support dir copy. It seems, that this parameter configuration is not supported by current ansible. 

copy module should be replaced by command modue [stackoverflow](https://stackoverflow.com/questions/35488433/ansible-copy-a-directory-content-to-another-directory)

**Comment by tomjirsa** [comment]
any update here?

**Comment by cermmik** [comment]
- [x]  Copy command updated.
- [ ] Need to update main readme for new provisioning

**Pull request merged**
